# Generated by Django 4.2.29 on 2026-03-05 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('total_rules', models.IntegerField(default=0)),
                ('passed_rules', models.IntegerField(default=0)),
                ('failed_rules', models.IntegerField(default=0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
            ],
            options={
                'db_table': 'quality_scores',
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('failed_rows', models.IntegerField(default=0)),
                ('total_rows', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.validationrule')),
            ],
            options={
                'db_table': 'check_results',
            },
        ),
    ]
