# Generated by Django 4.2.29 on 2026-03-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dataset_type', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(max_length=20)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(default='MEDIUM', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'validation_rules',
            },
        ),
    ]
