# Generated by Django 4.2.29 on 2026-03-06 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('HOURLY', 'Every hour'), ('DAILY', 'Every day'), ('WEEKLY', 'Every week'), ('MONTHLY', 'Every month')], default='DAILY', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(help_text='Dataset to run scheduled checks on.', on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
            ],
            options={
                'db_table': 'schedule_configs',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CHECK_RUN', 'Quality Check Run'), ('BATCH_RUN', 'Batch Check Run'), ('SCHEDULED_RUN', 'Scheduled Check Run'), ('RULE_CREATED', 'Rule Created'), ('RULE_UPDATED', 'Rule Updated'), ('RULE_DELETED', 'Rule Deleted')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasets.dataset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(default=70.0, help_text='Alert when quality score drops below this value (0-100).')),
                ('email_recipients', models.TextField(help_text='Comma-separated list of email addresses to notify.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(blank=True, help_text='If null, applies to all datasets as the global default.', null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
            ],
            options={
                'db_table': 'alert_configs',
            },
        ),
    ]
